from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, runtime_checkable

RUNTIME_HOST_EVENT_QUEUE_UPDATED = "queue_updated"
RUNTIME_HOST_EVENT_JOB_SUBMITTED = "job_submitted"
RUNTIME_HOST_EVENT_JOB_STARTED = "job_started"
RUNTIME_HOST_EVENT_JOB_FINISHED = "job_finished"
RUNTIME_HOST_EVENT_JOB_FAILED = "job_failed"
RUNTIME_HOST_EVENT_WATCHDOG_VIOLATION = "watchdog_violation"
RUNTIME_HOST_EVENT_QUEUE_EMPTY = "queue_empty"
RUNTIME_HOST_EVENT_QUEUE_STATUS = "queue_status"


@runtime_checkable
class RuntimeHostPort(Protocol):
    """Controller-facing runtime seam that remains stable across local and IPC hosts."""

    queue: Any
    job_queue: Any
    runner: Any
    history_store: Any
    auto_run_enabled: bool

    def register_callback(self, event: str, callback: Callable[..., None]) -> None: ...
    def set_status_callback(self, name: str, callback: Callable[..., None]) -> None: ...
    def set_event_dispatcher(self, dispatch_fn: Callable[[Callable[[], None]], None]) -> None: ...
    def set_job_lifecycle_logger(self, logger: Any | None) -> None: ...
    def set_activity_hooks(self, *, on_queue_activity=None, on_runner_activity=None) -> None: ...
    def register_completion_handler(self, handler: Callable[[Any, Any], None]) -> None: ...
    def submit_job_with_run_mode(self, job: Any, *, emit_queue_updated: bool = True) -> None: ...
    def submit_queued(self, job: Any, *, emit_queue_updated: bool = True) -> None: ...
    def enqueue(self, job: Any, *, emit_queue_updated: bool = True) -> None: ...
    def run_now(self, job: Any) -> None: ...
    def enqueue_njrs(self, njrs: list[Any], run_request: Any) -> list[str]: ...
    def run_next_now(self) -> None: ...
    def cancel_current(self, *, return_to_queue: bool = False) -> Any: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def replace_runner(self, value: Any) -> None: ...
    def get_diagnostics_snapshot(self) -> dict[str, Any]: ...
    def describe_protocol(self) -> dict[str, Any]: ...


__all__ = [
    "RUNTIME_HOST_EVENT_JOB_FAILED",
    "RUNTIME_HOST_EVENT_JOB_FINISHED",
    "RUNTIME_HOST_EVENT_JOB_STARTED",
    "RUNTIME_HOST_EVENT_JOB_SUBMITTED",
    "RUNTIME_HOST_EVENT_QUEUE_EMPTY",
    "RUNTIME_HOST_EVENT_QUEUE_STATUS",
    "RUNTIME_HOST_EVENT_QUEUE_UPDATED",
    "RUNTIME_HOST_EVENT_WATCHDOG_VIOLATION",
    "RuntimeHostPort",
]