from __future__ import annotations

from typing import Any


DEFAULT_PROMPT_OPTIMIZER_SETTINGS: dict[str, Any] = {
    "enabled": True,
    "optimize_positive": True,
    "optimize_negative": True,
    "dedupe_enabled": True,
    "preserve_lora_relative_order": True,
    "preserve_unknown_order": True,
    "log_before_after": True,
    "log_bucket_assignments": False,
    "warn_on_large_chunk_count": True,
    "large_chunk_warning_threshold": 18,
    "enable_score_based_classification": False,
    "allow_subject_anchor_boost": False,
    "subject_anchor_boost_min_chunk_count": 8,
    "opt_out_pipeline_names": [],
}


DEFAULT_POSITIVE_KEYWORDS: dict[str, tuple[str, ...]] = {
    "subject": (
        "portrait of",
        "beautiful woman",
        "beautiful man",
        "woman",
        "man",
        "girl",
        "boy",
        "person",
        "female",
        "male",
        "soldier",
        "warrior",
        "knight",
        "doctor",
        "astronaut",
    ),
    "environment": (
        "garden",
        "forest",
        "city",
        "street",
        "temple",
        "bedroom",
        "office",
        "castle",
        "beach",
        "mountains",
        "snow",
        "rain",
        "autumn",
        "maple trees",
        "stone path",
        "indoors",
        "outdoors",
        "japanese garden",
    ),
    "pose_action": (
        "standing",
        "sitting",
        "walking",
        "running",
        "kneeling",
        "looking at viewer",
        "looking toward camera",
        "smiling",
        "full body",
        "upper body",
        "portrait",
        "close-up",
        "profile",
    ),
    "composition": (
        "centered",
        "symmetrical composition",
        "rule of thirds",
        "wide shot",
        "close shot",
    ),
    "lighting_atmosphere": (
        "cinematic lighting",
        "soft lighting",
        "dramatic lighting",
        "rim lighting",
        "backlighting",
        "volumetric lighting",
        "sunset light",
        "golden hour",
        "moody lighting",
        "warm glow",
        "fog",
    ),
    "camera_lens": (
        "85mm",
        "50mm",
        "35mm",
        "telephoto",
        "wide angle",
        "macro",
        "depth of field",
        "shallow depth of field",
        "bokeh",
        "professional photography",
        "dslr",
        "f/1.8",
        "f/2.8",
        "lens",
    ),
    "material_surface_detail": (
        "natural skin texture",
        "detailed skin",
        "freckles",
        "hair detail",
        "fabric detail",
        "detailed eyes",
        "detailed face",
        "skin pores",
        "glossy",
        "matte",
    ),
    "style_medium": (
        "photorealistic",
        "realistic",
        "hyperrealistic",
        "cinematic",
        "film still",
        "digital painting",
        "oil painting",
        "anime",
        "illustration",
        "concept art",
        "3d render",
    ),
    "quality_tokens": (
        "masterpiece",
        "best quality",
        "ultra detailed",
        "highly detailed",
        "8k",
        "4k",
        "absurdres",
        "sharp focus",
    ),
}


DEFAULT_NEGATIVE_KEYWORDS: dict[str, tuple[str, ...]] = {
    "anatomy_defects": (
        "bad anatomy",
        "deformed",
        "mutated",
        "malformed",
        "extra limbs",
        "missing limbs",
        "bad proportions",
        "twisted body",
    ),
    "face_hand_defects": (
        "bad hands",
        "extra fingers",
        "missing fingers",
        "mutated hands",
        "deformed hands",
        "bad face",
        "deformed face",
        "ugly face",
        "asymmetrical eyes",
    ),
    "render_artifacts": (
        "blurry",
        "low quality",
        "jpeg artifacts",
        "artifact",
        "grainy",
        "noisy",
        "oversaturated",
        "overexposed",
        "underexposed",
        "washed out",
        "duplicate",
    ),
    "composition_defects": (
        "cropped",
        "out of frame",
        "cut off",
        "bad composition",
        "poor framing",
        "off center",
        "extra people",
        "multiple views",
    ),
    "text_logo_watermark": (
        "text",
        "watermark",
        "logo",
        "signature",
        "caption",
        "username",
    ),
    "style_blockers": (
        "cartoon",
        "anime",
        "3d",
        "cgi",
        "painting",
        "sketch",
    ),
}
